### ISSUE TITLE
[Query] Minimum number of training examples for overfitting 

### ISSUE THREAD

**Issue by saurabhvyas** [philipperemy/tensorflow-ctc-speech-recognition#1]
I am new to deep learning and end to end speech recognition , I am looking to create a model which can predict 3 words , "red" , "green" or "blue" , I want the model to over fit these 3 training examples , so do you think it's possible with ctc training for such a small dataset , or do I need a huge dataset to learn essential features and then overfit with these 3 additional examples ?

Thanks

**Comment by philipperemy** [comment]
You don't need CTC for that.

All what you need is to extract some relevant features yourself, like MFCC.

Then you can apply a Conv Net (or any statistical classifier) directly onto those features.

CTC is great when looking at sentences. In your case, CTC would work but you would need a lot more of data.

**Comment by saurabhvyas** [comment]
That explains , why after even 10,000 epochs and batch size of 1 , It didn't learn anything meaningful with 2 examples , Thanks !
