### ISSUE TITLE
Generate your cache please

### ISSUE THREAD

**Issue by AsmaaAlr** [philipperemy/tensorflow-ctc-speech-recognition#2]
i keep getting this message, I'm not sure what to do.

there is no path '/Volumes/Transcend/VCTK-Corpus/'
should i create it and put the dropbox file in it?

{'AUDIO': {'SAMPLE_RATE': 8000,
           'VCTK_CORPUS_PATH': '/Volumes/Transcend/VCTK-Corpus/'}}
Initializing AudioReader()
audio_dir = /Volumes/Transcend/VCTK-Corpus/
sample_rate = 8000
speakers_sub_list = ['p225']
Nothing found at /tmp/tensorflow-ctc-speech-recognition/. Generating all the caches now.
Traceback (most recent call last):
  File "generate_audio_cache.py", line 18, in <module>
    generate()
  File "generate_audio_cache.py", line 14, in generate
    speakers_sub_list=speakers_sub_list)
  File "/Users/XXXX/Desktop/file/ctc-speech/audio_reader.py", line 59, in __init__
    assert len(files) != 0, 'Generate your cache please.'
AssertionError: Generate your cache please.

**Comment by philipperemy** [comment]
Ive just received your email. You have to generate your cache first by running:

```
python3 generate_audio_cache.py
```

Make sure you download the relevant files beforehand: https://www.dropbox.com/s/xecprghgwbbuk3m/vctk-pc225.tar.gz?dl=1
