### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ccpyo** [philipperemy/tensorflow-ctc-speech-recognition#4]
I have been download the smaller dataset and whole dataset,but there's some problem whlie I'm running generate_audio_cache.py.Did I put the dataset in the wrong folder?I only change the datapath in conf.json.

Here's the datapath where I save dataset and code.
C:\Users\OAQ\ctc-speech
C:\tmp\VCTK-Corpus

C:\Users\OAQ\ctc-speech>python generate_audio_cache.py
{'AUDIO': {'SAMPLE_RATE': 8000, 'VCTK_CORPUS_PATH': '/tmp/VCTK-Corpus/'}}
Initializing AudioReader()
audio_dir = /tmp/VCTK-Corpus/
sample_rate = 8000
speakers_sub_list = ['p225']
Nothing found at /tmp/tensorflow-ctc-speech-recognition/. Generating all the caches now.
Found 44257 files in total in /tmp/VCTK-Corpus/.
0 files correspond to the speaker list ['p225'].
Traceback (most recent call last):
  File "generate_audio_cache.py", line 18, in <module>
    generate()
  File "generate_audio_cache.py", line 14, in generate
    speakers_sub_list=speakers_sub_list)
  File "C:\Users\OAQ\ctc-speech\audio_reader.py", line 65, in __init__
    assert len(files) != 0
AssertionError

**Comment by InSightSuen** [comment]
the VCTK_CORPUS_PATH should be like  "*/VCTK-Corpus/wav48"

**Comment by philipperemy** [comment]
@InSightSuen thanks for answering :)

**Comment by ccpyo** [comment]
Thanks a lot, but I have another question for it.I make it have the correct datapath, but it shows another error now.It doesn't make any cache file in that directory.Did I miss any step with that?

C:\Users\OAQ\ctc-speech>python generate_audio_cache.py
{'AUDIO': {'SAMPLE_RATE': 8000, 'VCTK_CORPUS_PATH': '/tmp/p225/wav48/'}}
Initializing AudioReader()
audio_dir = /tmp/p225/wav48/
sample_rate = 8000
speakers_sub_list = ['p225']
Nothing found at /tmp/tensorflow-ctc-speech-recognition/. Generating all the caches now.
Found 231 files in total in /tmp/p225/wav48/.
231 files correspond to the speaker list ['p225'].
Traceback (most recent call last):
  File "generate_audio_cache.py", line 18, in <module>
    generate()
  File "generate_audio_cache.py", line 14, in generate
    speakers_sub_list=speakers_sub_list)
  File "C:\Users\OAQ\ctc-speech\audio_reader.py", line 77, in __init__
    with open(tmp_filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tensorflow-ctc-speech-recognition/wav48\\p225\\p225_001_cache.pkl'

**Comment by philipperemy** [comment]
@ccpyo yes you have to generate the cache.

**Comment by philipperemy** [comment]
`python3 generate_audio_cache.py`

**Comment by philipperemy** [comment]
https://github.com/philipperemy/tensorflow-ctc-speech-recognition#how-to-get-started

**Comment by ccpyo** [comment]
I have already run that code, and that error message was occurred while I'm trying to generate the cache.

**Comment by philipperemy** [comment]
@ccpyo maybe because you're running on Windows.
