### ISSUE TITLE
What does number of feature do?

### ISSUE THREAD

**Issue by gabegaz** [philipperemy/tensorflow-ctc-speech-recognition#5]
Thanks philipperemy for this work,

1) What does number of features do? Couldnot understand that

2) I just want to the number of layers to something like 4 or 5 but there is a dimension issue. Is there any other adjustment i should make other than increase the number of layers?

Thanks

**Comment by philipperemy** [comment]
@getabegaz thank you!
1. It's the number of features for each timestep. In this case it's the number of MFCCs.
2. Yeah seems like there's a dimension issue. I'll search for a way to fix it.

**Comment by philipperemy** [comment]
Well dynamic_rnn is deprecated anyway. So I guess it's better to upgrade the APIs to V2. I'll try to find some time to do that.
