### ISSUE TITLE
What is INDEX?

### ISSUE THREAD

**Issue by mehadi-trackrep** [philipperemy/tensorflow-ctc-speech-recognition#6]
What is INDEX here and how we can use it for other languages?
Actually, what portions of code are needed to change?
Please give me the instructions.

**Comment by philipperemy** [comment]
@mehadi-trackrep this implementation is just an example (tutorial) to show how to use CTC. You're not likely to go anymore (I mean having state of the art results) with this code.
I updated the code. INDEX is no longer here. Should be clearer now.
